apiVersion: v1
kind: Service
metadata:
  name: argocd-server-nodeport
  namespace: argocd-system
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: argocd-server
  ports:
    - name: server
      port: 80
      targetPort: 8080
      nodePort: 30080
    - name: grpc
      port: 443
      targetPort: 8080
      nodePort: 30443