apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kimai
  namespace: argocd-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kimai
    repoURL: https://github.com/AdnanAlagic/devops-practice
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true