apiVersion: v1
kind: PersistentVolume
metadata:
  name: kimai-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/kimai
  persistentVolumeReclaimPolicy: Retain