apiVersion: v1
kind: Service
metadata:
  name: kimai-service
  namespace: kimai
spec:
  type: NodePort
  selector:
    app: kimai
  ports:
    - port: 8001
      targetPort: 8001
      nodePort: 30083